#!/bin/sh
set -e
. "${MCDDIR}"/functions.sh
#Arch Linux installer plugin for multicd.sh
#version 20120426
#Copyright (c) 2012 Isaac Schemm
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in
#all copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#THE SOFTWARE.
if [ $1 = links ];then
	#Only one will be included
	echo "antergos-*-i686.iso antergos.iso none"
	echo "antergos-*-x86_64.iso antergos.iso none"
elif [ $1 = scan ];then
	if [ -f antergos.iso ];then
		echo "Antergos Linux"
	fi
elif [ $1 = copy ];then
	if [ -f antergos.iso ];then
		echo "Copying Antergos Linux..."
		mcdmount antergos
		cp -r "${MNT}"/antergos/arch "${WORK}"/antergos
		umcdmount antergos
	fi
elif [ $1 = writecfg ];then
if [ -f antergos.iso ];then
	if [ -f "${MNT}"/boot/syslinux/syslinux_arch32.cfg ] && [ -f "${MNT}"/boot/syslinux/syslinux_arch64.cfg ];then
		echo "label antergos
		menu label --> ^Antergos Linux ($(getVersion antergos))
		KERNEL /antergos/boot/syslinux/ifcpu64.c32
		APPEND have64 -- nohave64
	
		LABEL have64
		MENU HIDE
		CONFIG /antergos/boot/syslinux/syslinux_both.cfg
		APPEND /antergos/boot/syslinux/
	
		LABEL nohave64
		MENU HIDE
		CONFIG /antergos/boot/syslinux/syslinux_32only.cfg
		APPEND /antergos/boot/syslinux/
		" >> "${WORK}"/boot/isolinux/isolinux.cfg
		for i in 32 64;do
		    sed -i -e "s/antergosisolabel=[A-Za-z0-9_]*/antergosisolabel=${CDLABEL}/" \
		    "${WORK}"/antergos/boot/syslinux/syslinux_antergos${i}.cfg
		done
		echo "
		label back
		menu label ^Back to main menu
		config /boot/isolinux/isolinux.cfg
		append /boot/isolinux
		" >> "${WORK}"/antergos/boot/syslinux/syslinux_tail.cfg
	else
		echo "LABEL antergos
		MENU LABEL --> ^Antergos Linux ($(getVersion antergos))
		CONFIG /arch/boot/syslinux/syslinux.cfg
		APPEND /arch/boot/syslinux/
		" >> "${WORK}"/boot/isolinux/isolinux.cfg
		for i in "${WORK}"/antergos/boot/syslinux/*.cfg;do
		    sed -i -e "s/antergosisolabel=[A-Za-z0-9_]*/antergosisolabel=${CDLABEL}/" \
		    "$i"
		done
		echo "
		LABEL back
		MENU LABEL ^Back to main menu..
		CONFIG /boot/isolinux/isolinux.cfg
		APPEND /boot/isolinux
		" >> "${WORK}"/antergos/boot/syslinux/syslinux_tail.cfg
	fi
fi
else
	echo "Usage: $0 {links|scan|copy|writecfg}"
	echo "Use only from within multicd.sh or a compatible script!"
	echo "Don't use this plugin script on its own!"
fi
